before_script:
    - date
    - uname -a
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - make versions	
    - printenv | sort

netflix:
    image: "python:latest"
    script:
    - ls -al
    # - make test