before_script:
    - date
    - uname -a
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - make versions	
    - printenv | sort
    - wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
    - chmod +x cloud_sql_proxy

Website:
    image: "python:latest"
    script:
    - ls -al
    - make test