# [START flask_app]
runtime: python37
entrypoint: gunicorn -b :$PORT website.main:app

# This configures Google App Engine to serve the files in the app's static
# directory.
handlers:
- url: /static
  static_dir: website/static/
- url: /media
  static_dir: Website/media/

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto


env_variables:
    # Replace user, password, database, and instance connection name with the values obtained
    # when configuring your Cloud SQL instance.
    SQLALCHEMY_DATABASE_URI: >-
      postgresql+psycopg2://postgres:password123@/austin-music?host=/cloudsql/cs329e:us-central1:austin-music

# Replace project and instance with the values obtained  when configuring your
# Cloud SQL instance.
beta_settings:
    cloud_sql_instances: cs329e:us-central1:austin-music


# [END flask_app]